### PR TITLE
When this.props.onCloseTab() returns false, it does not close

### PR DESCRIPTION
**Pull request by kulelikule**
I increase the judgment logic, When this.props.onCloseTab() returns false, it does not close

### CODE REVIEW

**Comment by themre** [comment]
This callback `onClose` was for developer to decide when to use it. So for example I could have some analytics where I would trigger event in `onClose` callback, but I would still like to leave closeable-tabs to behave normally. Can you explain what was the use-case to have this logic implemented?

**Comment by kulelikule** [comment]
I need the user to confirm twice whether to close this tab. If the user misuses, then I will return false, which prevents the tab from closing.

**Comment by kulelikule** [comment]
If you feel that there is no problem, can you publish a new version of the npm package after merging the code? Thanks.

**Comment by themre** [comment]
Ah ok, I understand. I think it would be best to rewrite this component in such a way that state is controlled outside of tabs. Haven't touched this in a while and it was my first react component :) but for now I will merge it and will try yo rewrite this so we have this component only as a view component, without state.

**Comment by themre** [comment]
published under version 1.1.2.

**Pull request merged**
